version: '2'
services:
  cakephp:
    build: .
    ports:
      - "4000:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html/
    environment:
      - SECURITY_SALT=ashjg23697sds97139871298ashk  
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
  mysql:
    image: mysql:5.6.36
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cakephp
volumes:
    mysql_data: